CREATE TABLE files(
	id INT auto_increment PRIMARY KEY,
	name VARCHAR(512) NOT NULL DEFAULT '',
	type VARCHAR(512) NOT NULL DEFAULT '',
	size INT NOT NULL DEFAULT 0,
	created INT NOT NULL DEFAULT 0
);

ALTER TABLE files ADD COLUMN alias VARCHAR(512) NOT NULL DEFAULT '';